### ISSUE TITLE
<DonutLabel> giving issue while using the map function on <DonutElement>

### ISSUE THREAD

**Issue by karanwadhwani-tudip** [gsdeveloper/react-donut-component#1]
Hi @guilhermesamuel,
I need your help with an issue while using the <DonutMultiple> component of react-donut-component:

Details:

I am using <DonutMultiple> component of react-donut-component to display a donut chart with dynamic values:
- I am using the loop on the <DonutElement> to display the bars with the respective values I am receiving from an API.
- I am using <DonutLabel> to display the label for the donut chart.
- While I am using the object.map() function to loop through the values and <DonutLabel> to display the label I am receiving the following error:
Cannot find the name of undefined.

Here is the code example I am using:

const donutData = [
  { 
    value: 35, 
    color: '#4a25cd'
  }, 
  { 
    value: 75, 
    color: '#4a2510'
  }, 
  {
    value: 20, 
    color: '#1025cd'
  }
]

<DonutMultiple size={80} linecap={'round'} animate={true}>
      {
           donutData.map(item => 
              <DonutElement color={item.color}>
                    {item.value}
               </DonutElement>
           )
      }
      <DonutLabel>50</DonutLabel>
</DonutMultiple>
                  
Can you please help me with the same?

**Comment by guitheengineer** [comment]
Hi @karanwadhwani-tudip, your code is almost correct, the only problem is that the values inside DonutMultiple have to be used with the DonutElement component, so you should return them when doing a map:

```jsx
{donutData.map((el, i) => (
    <DonutElement color={el.color} key={i}>
         {el.value}
    </DonutElement>
))}
```

[See this example I made for you](https://codesandbox.io/s/donut-multiple-example-l6o65?file=/src/App.tsx)

I hope this answer will help :)
